main/urls.py
from django.urls import path
from .views import (
    index,
    saveuser_db,
    RegisterView,
    change_password,
    LogoutUserView,
    profile_user,
    LoginUserView,
    add_employee_view,
    add_department_view,
    add_position_view,
    all_employees_view,
    all_position_view,
    all_departments_view,
    del_position,
    del_employee,
    del_department,
    edit,
)


app_name = "main"


urlpatterns = [
    path("", index, name="main"),
    path("saveuser/", saveuser_db, name="saveuser"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
    path("accounts/change_password/", change_password, name="change_password"),
    path("accounts/logout/", LogoutUserView.as_view(), name="logout"),
    path("accounts/profile/", profile_user, name="profile"),
    path("accounts/login/", LoginUserView.as_view(), name="login"),
    path("add_employee/", add_employee_view, name="add_employee"),
    path("employees/<int:id>/", all_employees_view, name="employee"),
    path("employees/", all_employees_view, name="employees"),
    path("employees/del_employee/<int:id>/", del_employee, name="del_employee"),
    path("add_department/", add_department_view, name="add_department"),
    path("departments/<int:id>/", all_departments_view, name="department"),
    path("departments/", all_departments_view, name="departments"),
    path(
        "departments/del_department/<int:id>/", del_department, name="del_departments"
    ),
    path("add_position/", add_position_view, name="add_position"),
    path("positions/<int:id>/", all_position_view, name="position"),
    path("positions/", all_position_view, name="positions"),
    path("positions/del_position/<int:id>/", del_position, name="del_position"),
    path("employees/<int:id>/edit/", edit, name="edit"),
]

web_for_company/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class DepartmentModel(models.Model):
    name = models.CharField(max_length=80, db_index=True)
    slug = models.SlugField(max_length=80, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        verbose_name = "Подразделение предприятия"
        verbose_name_plural = "Подразделения предприятия"


class PositionModel(models.Model):
    name = models.CharField(max_length=80, db_index=True)
    slug = models.SlugField(max_length=80, db_index=True)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ("name",)
        verbose_name = "Должность"
        verbose_name_plural = "Должности"


class EmployeeModel(models.Model):
    department = models.ForeignKey(
        DepartmentModel,
        related_name="employeed",
        on_delete=models.PROTECT,
        verbose_name="Отдел",
    )
    position = models.ForeignKey(
        PositionModel,
        related_name="employeep",
        on_delete=models.PROTECT,
        verbose_name="Должность",
    )
    name = models.CharField(
        max_length=80, db_index=True, verbose_name="Имя Отчество сотрудника"
    )
    surname = models.CharField(
        max_length=50, db_index=True, verbose_name="Фамилия сотрудника"
    )
    phone = models.CharField(
        max_length=30,
        blank=True,
        null=True,
        db_index=True,
        unique=True,
        verbose_name="Номер телефона",
    )
    email = models.CharField(
        max_length=30, db_index=True, null=True, verbose_name="Email"
    )
    hiring_date = models.DateField(
        blank=True, null=True, db_index=True, verbose_name="Дата трудоустройства"
    )
    termination_date = models.DateField(
        blank=True, null=True, db_index=True, verbose_name="Дата увольнения"
    )
    experience = models.PositiveIntegerField(
        blank=True, null=True, db_index=True, verbose_name="Стаж работы"
    )
    birthday = models.CharField(
        max_length=30, blank=True, null=True, verbose_name="Дата рождения"
    )
    description = models.TextField(blank=True, null=True, verbose_name="О сотруднике")

    def __str__(self):
        return f"{self.surname}"

    class Meta:
        ordering = ("surname",)
        verbose_name = "Сотрудник"
        verbose_name_plural = "Сотрудники"


class DataModelUser(models.Model):
    login = models.CharField(unique=True, max_length=100)
    password = models.CharField(max_length=150)


class ExtendUser(AbstractUser):
    is_activated = models.BooleanField(
        default=True, db_index=True, verbose_name="Прошел активацию?"
    )

    class Meta(AbstractUser.Meta):
        pass

main/forms.py
from django.core.exceptions import ValidationError
from django.contrib.auth import password_validation
from .models import *
from django import forms


class AccountLoginForm(forms.Form):
    login = forms.CharField(max_length=100, label="Логин")
    password = forms.CharField(
        widget=forms.PasswordInput, max_length=100, label="Пароль"
    )


class ChangePasswordForm(forms.ModelForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput, max_length=75, label="Старый пароль"
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput, max_length=75, label="Новый пароль"
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput, max_length=75, label="Повторить пароль"
    )

    class Meta:
        model = ExtendUser
        fields = ["old_password", "new_password1", "new_password2"]


class UserFormRegister(forms.ModelForm):
    email = forms.EmailField(required=True, label="Адрес электронной почты")
    password1 = forms.CharField(
        widget=forms.PasswordInput,
        label="Пароль",
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput,
        label="Повторить пароль",
        help_text="Введите пароль повторно для проверки",
    )

    def clean_password1(self):
        # валидный ли пароль
        password1 = self.cleaned_data["password1"]
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 and password2 and password1 != password2:
            errors = {
                "password2": ValidationError(
                    "Введенные пароли не совпадают", code="password_mismatch"
                )
            }
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = True
        user.is_activated = False
        if commit:
            user.save()
        return user

    class Meta:
        model = ExtendUser
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
        )


class AddEmployeeForm(forms.ModelForm):
    class Meta:
        model = EmployeeModel
        fields = "__all__"


class AddPositionForm(forms.ModelForm):
    class Meta:
        model = PositionModel
        fields = ("name",)
        labels = {"name": "Название должности"}


class AddDepartmentForm(forms.ModelForm):
    class Meta:
        model = DepartmentModel
        fields = ("name",)
        labels = {"name": "Название отедела"}


class EditEmployeeForm(forms.ModelForm):
    class Meta:
        model = EmployeeModel
        fields = ("department",)

main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, LoginView
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import (
    ChangePasswordForm,
    UserFormRegister,
    AddDepartmentForm,
    AddPositionForm,
    AddEmployeeForm,
    EditEmployeeForm,
)
from .models import (
    DataModelUser,
    ExtendUser,
    DepartmentModel,
    PositionModel,
    EmployeeModel,
)


def index(request):
    data = request.POST
    return render(request, "pages/main.html")


def saveuser_db(request):
    login = request.POST.get("login")
    password = request.POST.get("password")
    user = DataModelUser.objects.get(login=login)
    if check_password(password, user.password):
        print(password)
        return HttpResponse("Ты вошел")

    return render(request, "pages/main.html")


class RegisterView(CreateView):
    model = ExtendUser
    template_name = "user/user_register.html"
    form_class = UserFormRegister
    success_url = reverse_lazy("main:profile")


@login_required
def change_password(request):
    if request.method == "POST":
        passwords = request.POST
        user = request.user
        old_password = passwords["old_password"]
        new_password1 = passwords["new_password1"]
        new_password2 = passwords["new_password2"]
        print(old_password)
        if check_password(old_password, user.password):
            if new_password1 == new_password2:
                user.set_password(new_password1)
                user.save()
                message = "Ваш пароль успешно изменен"
                return render(
                    request, "user/change_password.html", context={"message": message}
                )
            else:
                error = "Пароли не совпадают"
                return render(request, "user/profile.html", context={"error": error})
    form = ChangePasswordForm()
    return render(request, "user/change_password.html", context={"form": form})


class LogoutUserView(LoginRequiredMixin, LogoutView):
    template_name = "pages/main.html"


@login_required
def profile_user(request):
    data = request.POST
    dataDepartment = DepartmentModel.objects.all()
    dataPosition = PositionModel.objects.all()
    dataEmployee = EmployeeModel.objects.all()

    return render(
        request,
        "user/profile.html",
        {
            "dataDepartment": dataDepartment,
            "dataPosition": dataPosition,
            "dataEmployee": dataEmployee,
        },
    )


class LoginUserView(LoginView):
    template_name = "user/login.html"
    redirect_field_name = "profile.html"


def all_employees_view(request, id=None):
    all_employees = EmployeeModel.objects.prefetch_related().all()
    context = {"all_employees": all_employees}
    if id:
        employee = EmployeeModel.objects.get(id=id)
        context["employee"] = employee
    return render(request, "user/employees.html", context)


def all_departments_view(request, id=None):
    all_departments = DepartmentModel.objects.prefetch_related().all()
    context = {"all_departments": all_departments}
    if id:
        department = DepartmentModel.objects.get(id=id)
        context["department"] = department
    return render(request, "pages/departments.html", context)


def all_position_view(request, id=None):
    all_positions = PositionModel.objects.prefetch_related().all()
    context = {"all_positions": all_positions}
    if id:
        position = PositionModel.objects.get(id=id)
        context["position"] = position
    return render(request, "pages/positions.html", context)


def add_employee_view(request):
    newemp = EmployeeModel.objects.all()
    if request.method == "POST":
        newemp_form = AddEmployeeForm(request.POST)
        if newemp_form.is_valid():
            newemp_form.save()
            return render(
                request,
                "user/profile.html",
                {"text": "Сотрудник добавлен", "newemp": newemp},
            )
        else:
            return render(
                request,
                "user/add_employee.html",
                {"text": "Форма оформлена не правильно", "newemp": newemp},
            )
    else:
        newemp_form = AddEmployeeForm()
        return render(request, "user/add_employee.html", {"form": newemp_form})


def add_department_view(request):
    newdep = DepartmentModel.objects.all()
    if request.method == "POST":
        newdep_form = AddDepartmentForm(request.POST)
        if newdep_form.is_valid():
            newdep_form.save()
            return render(
                request,
                "user/profile.html",
                {"text": "Подразделение добавлено", "newdep": newdep},
            )
        else:
            return render(
                request,
                "pages/add_department.html",
                {"text": "Форма оформлена не правильно", "newdep": newdep},
            )
    else:
        newdep_form = AddDepartmentForm()
        return render(request, "pages/add_department.html", {"form": newdep_form})


def add_position_view(request):
    newpos = PositionModel.objects.all()
    if request.method == "POST":
        newpos_form = AddPositionForm(request.POST)
        if newpos_form.is_valid():
            newpos_form.save()
            return render(
                request,
                "user/profile.html",
                {"text": "Должность добавлена", "newpos": newpos},
            )
        else:
            return render(
                request,
                "pages/add_position.html",
                {"text": "Форма оформлена не правильно", "newpos": newpos},
            )
    else:
        newpos_form = AddPositionForm()
        return render(request, "pages/add_position.html", {"form": newpos_form})


def edit(request, id):
    edit_employee = EmployeeModel.objects.get(id=id)

    if request.method == "POST":
        edit_form = EditEmployeeForm(request.POST, instance=edit_employee)
        if edit_form.is_valid():
            edit_form.save()

            return render(
                request,
                "user/profile.html",
                {"text": "Сотрудник переведен в другой отдел", "edit_form": edit_form},
            )
        else:
            return render(
                request,
                "user/edit_employee.html",
                {"text": "Форма оформлена не правильно", "edit_form": edit_form},
            )
    else:
        edit_form = EditEmployeeForm()
        return render(request, "user/edit_employee.html", {"form": edit_form})


def del_position(request, id=None):
    position = PositionModel.objects.get(id=id)
    position.delete()
    return render(request, "user/profile.html", {"text": "Должность удалена"})


def del_employee(request, id=None):
    employee = EmployeeModel.objects.get(id=id)
    employee.delete()
    return render(request, "user/profile.html", {"text": "Сотрудник удален"})


def del_department(request, id=None):
    department = DepartmentModel.objects.get(id=id)
    department.delete()
    return render(request, "user/profile.html", {"text": "Подразделение удалено"})

main/templates/pages/add_department.html
{% extends 'user/profile.html' %}
{% load static %}
{% block title %}
    Добавить отдел
{% endblock %}
{% block content %}

<div class="form-request">
    <h2 class="h_manager">Добавление отдела</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        <table>
        {% csrf_token %}

       {{form.as_table}}
            <tr><td><input type="submit" value="Добавить отдел"></td></tr>
            </table>
            {{text}}
    </form>
</div>

{% endblock %}

main/templates/pages/add_position.html
{% extends 'user/profile.html' %}
{% load static %}
{% block title %}
    Добавить должность
{% endblock %}
{% block content %}

<div class="form-request">
    <h2 class="h_manager">Добавление должности</h2>
    <form action="" method="POST" enctype="multipart/form-data">
        <table>
        {% csrf_token %}

       {{form.as_table}}
            <tr><td><input type="submit" value="Добавить должность"></td></tr>
            </table>
            {{text}}
    </form>
</div>

{% endblock %}

main/templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <title>{% block title %} Веб приложение {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header >
        <div class="header">
            <div class="wrapper">
                <div class="header_wrapper_nav">
                    <nav class="header__nav">
                        <h3>Добро пожаловать</h3>
                        {% if user.is_authenticated %}
                        <h3>{{ request.user}} !</h3>
                        {% endif %}
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!--Header end-->

     {% block content %}

    {% endblock %}

</body>
</html>

main/templates/pages/departments.html
{% extends 'user/profile.html' %}
{% load static %}
{% block title %}
    Справочник подразделений
{% endblock %}
{% block content %}
<div >
    <button class="add_btn"><a href="{% url 'main:add_department' %}" >Добавить подразделение предприятия</a></button>
</div>


<h2 class="h_manager">Сотрудники подразделения</h2>
    <div class="cost_pr">
         <table class="table_profile" width = "100%" border = "1">
             <tr>
                 <th class="">
                     <h5>Название подразделения</h5>
                 </th>
                 <th class="">
                     <h5>Фамилии сотрудников</h5>
                 </th>
             </tr>
             <tr>
                 <td>{{department.name}}</td>
                 <td>{{department.employeed.all|join:","}}</td>
             </tr>
         </table>

<h2 class="h_manager">Справочник подразделений предприятия</h2>
    <div class="cost_pr">
         <table class="table_profile" width = "100%" border = "1">
             <tr>
                 <th class="">
                     <h5>Все подразделения</h5>
                 </th>
                 <th class="">
                     <h5>Все сотрудники подразделения</h5>
                 </th>
             </tr>
             {% for item in all_departments %}
             <tr>
                 <td class="td">
                    <a href="{% url 'main:department' item.id %}" >{{item}}</a>
                 </td>
                 <td class="td">
                    <a href="{% url 'main:department' item.id %}" >Фамилии сотрудников отдела</a>
                 </td>
                  <td class="td"><a href="del_department/{{item.id}}">Удалить отдел </a></td>
                <div>
                    <h1>{{text}}</h1>
                </div>
             </tr>
             {% endfor %}
         </table>
{% endblock %}
            </div>

main/templates/pages/main.html
{% extends 'pages/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block content %}
<section class="wrapper">
    <div class="main_page">
        <div class="main_inner">
            <div class="log">
                {% if user.is_authenticated %}
                <a href="{% url 'main:logout' %}" class="log_reg_inner">Выход</a>
                <a href="{% url 'main:change_password' %}" class="log_reg_inner">Сменить пароль</a>
                {% else %}
                <a href="{% url 'main:login' %}" class="log_reg_inner">Вход в приложение</a>
{%block navbar%}
    <a href="{% url 'main:register' %}" class="log_reg_inner">Регистрация</a>
    <a href="{% url 'main:logout' %}" class="log_reg_inner">Выход</a>
    <a href="{% url 'main:change_password' %}" class="log_reg_inner">Сменить пароль</a>
    <div class="message_error">{{error}}</div>
{% endblock %}
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

main/templates/pages/positions.html
{% extends 'user/profile.html' %}
{% load static %}
{% block title %}
    Справочник должностей
{% endblock %}
{% block content %}

<div >
    <button class="add_btn"><a href="{% url 'main:add_position' %}" >Добавить должность</a></button>
</div>

<h2 class="h_manager">Сотрудники </h2>
    <div class="cost_pr">
         <table class="table_profile" width = "100%" border = "1">
             <tr>
                 <th class="">
                     <h5>Название должности</h5>
                 </th>
                 <th class="">
                     <h5>Фамилии сотрудников</h5>
                 </th>
             </tr>
             <tr>
                 <td>{{position.name}}</td>
                 <td>{{position.employeep.all|join:","}}</td>
             </tr>
         </table>

<h2 class="h_manager">Справочник должностей предприятия</h2>
    <div class="cost_pr">
         <table class="table_profile" width = "100%" border = "1">
             <tr>
                 <th class="">
                     <h5>Должность</h5>
                 </th>
             </tr>
             {% for item in all_positions %}
             <tr>
                 <td class="td">
                    <a href="{% url 'main:position' item.id %}" >{{item}}</a>
                 </td>
                 <td class="td">
                    <a href="{% url 'main:position' item.id %}" >Фамилии сотрудников </a>
                 </td>
                 <td class="td"><a href="del_position/{{item.id}}">Удалить должность</a></td>

                 <h1>{{text}}</h1>

             </tr>
             {% endfor %}
         </table>
{% endblock %}
    </div>
    </div>